site_url: https://elclaustro.cl
display_url: https://elclaustro.cl

backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: main
  auth_scope: repo
  open_authoring: true
  squash_merges: true
open_authoring: true
publish_mode: editorial_workflow
logo_url: "https://elclaustro.cl/images/logo.svg"
locale: es
# local_backend: true
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "posts"
    folder: "content/posts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - { label: "Categories", name: "categories", widget: "list", item_widget: "select", default: ["Noticias"], options: [ "Columnas", "Contenido Enviado", "Destacados", "Discos, Videos y Playlists", "Entrevistas", "Noticias" ] }
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Type"
        name: "type"
        widget: "hidden"
        type: "string"
        default: "post"
      - label: "Body"
        name: "body"
        widget: "markdown"

