

backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: staging
  open_authoring: true
media_folder: static/images
public_folder: images/
publish_mode: editorial_workflow
logo_url: "https://elclaustro.cl/images/logo.svg"
collections:
    - name: Ingresa tu publicación
      label: post
      folder: "content/posts"
      create: true
      slug: "{{title}}"
      image: "{{image}}"
      type: post
      categories:
        - Noticias
        - Contenido Enviado
      fields:
      - {label: "type", name: "type", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen destacada", name: "image", widget: "image"}
      - {label: "Body", name: "body" , widget: "markdown"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "draft", name: "draft", default: "true" }
      - {label: "tags", name: "tags", widget: "list"}
      - {label: "Categoría", name: "categories", widget: "list"}

