site_url: https://test.elclaustro.cl
display_url: https://test.elclaustro.cl

backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: staging
  auth_scope: repo
  open_authoring: true
  squash_merges: true
open_authoring: true
publish_mode: editorial_workflow
logo_url: "https://elclaustro.cl/images/logo.svg"
locale: es
# local_backend: true
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "posts"
    folder: "content/posts"
    create: true
    
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "markdown"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Preview"
        name: "preview"
        widget: "image"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Categories"
        name: "categories"
        widget: "list"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Last Modified"
        name: "lastmod"
        widget: "datetime"
      - label: "URL"
        name: "url"
        widget: "string"
        default:
          function: |
            (formValues) => formValues.title.toLowerCase().replace(/\s/g, '-')
      - label: "Type"
        name: "type"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Keywords"
        name: "keywords"
        widget: "list"
